### ISSUE TITLE
[PE-D][Tester C] Unclear error message shown when deleting a negative index

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F13-3/tp#112] opened 2023-04-01 00:35 UTC
![image.png](https://raw.githubusercontent.com/nicholas132000/ped/main/files/81147845-a271-4308-a344-93b4b40a7ae8.png)

I think the error message shown when deleting a negative index could be made clearer, because the current message shown is not exactly clear to the user 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nicholas132000/ped#5

**Comment by matthew-liu-zhenjie** [comment] 2023-04-09 09:42
Duplicate of #124. Fixed by #152

**Closed by matthew-liu-zhenjie** 2023-04-09 09:42 UTC
